name: Compile LLink x86 Linux 
on: workflow_dispatch
jobs:
  Linux-x86-64-v8:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.2
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64-v7
    steps:
      - name: Install build tools
        run: |
          apt-get -y update
          apt-get -y install build-essential
          apt-get -y install libuv1-dev

      - name: Install Git in container
        run: |
          apt-get -y update
          apt-get -y install git
          # one time fix to avoid permission problems later on
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         
          token: ${{ secrets.GH_TOKEN }}           

      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          wolframscript -script ./Scripts/BuildLibrary.wls /usr/include/ /usr/lib/x86_64-linux-gnu/libuv.so

      - name: Commit files
        run: |
          git config pull.rebase false        
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LibraryResources/
          git commit -m "Add binary for ${{ env.WOLFRAM_SYSTEM_ID }}"
          git pull
          git push 


  Linux-x86-64-v7:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.1
      options: --user root

    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64-v7
    steps:
      - name: Install build tools
        run: |
          apt-get -y update
          apt-get -y install build-essential
          apt-get -y install libuv1-dev

      - name: Install Git in container
        run: |
          apt-get -y update
          apt-get -y install git
          # one time fix to avoid permission problems later on
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         
          token: ${{ secrets.GH_TOKEN }}           

      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          wolframscript -script ./Scripts/BuildLibrary.wls /usr/include/ /usr/lib/x86_64-linux-gnu/libuv.so

      - name: Commit files
        run: |
          git config pull.rebase false        
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LibraryResources/
          git commit -m "Add binary for ${{ env.WOLFRAM_SYSTEM_ID }}"
          git pull
          git push          